# Этот файл нужен, чтобы Python считал папку 'services' пакетом.
# Мы можем использовать его для удобного импорта, но сейчас оставим его простым.

# --- ИЗМЕНЕНИЕ ЗДЕСЬ: Убираем импорт несуществующей функции ---
# и импортируем новую, если это потребуется в будущем.
# Пока что для чистоты можно оставить его пустым или импортировать нужные функции.

# from .availability_service import get_manual_blocks, set_availability_for_period
# from .booking_service import ...
# from .pricing_service import ...
# from .property_service import ...
# from .review_service import ...
# from .user_service import ...

# На данном этапе для чистоты оставим файл пустым, 
# так как все импорты происходят напрямую из модулей.