"""Add timestamps and indexes to models

Revision ID: 8038227e4d27
Revises: a1daaa3bb07b
Create Date: 2025-06-28 14:06:10.996142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8038227e4d27'
down_revision: Union[str, None] = 'a1daaa3bb07b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_apscheduler_jobs_next_run_time', table_name='apscheduler_jobs')
    op.drop_table('apscheduler_jobs')
    op.add_column('bookings', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.alter_column('bookings', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('bookings_user_id_fkey', 'bookings', type_='foreignkey')
    op.drop_constraint('bookings_property_id_fkey', 'bookings', type_='foreignkey')
    op.create_foreign_key(None, 'bookings', 'properties', ['property_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'bookings', 'users', ['user_id'], ['telegram_id'], source_schema='public', referent_schema='public')
    op.add_column('price_rules', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.drop_constraint('price_rules_property_id_fkey', 'price_rules', type_='foreignkey')
    op.create_foreign_key(None, 'price_rules', 'properties', ['property_id'], ['id'], source_schema='public', referent_schema='public')
    op.add_column('properties', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.alter_column('properties', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_public_properties_district'), 'properties', ['district'], unique=False, schema='public')
    op.create_index(op.f('ix_public_properties_price_per_night'), 'properties', ['price_per_night'], unique=False, schema='public')
    op.drop_constraint('properties_owner_id_fkey', 'properties', type_='foreignkey')
    op.create_foreign_key(None, 'properties', 'users', ['owner_id'], ['telegram_id'], source_schema='public', referent_schema='public')
    op.add_column('property_media', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.drop_constraint('property_media_property_id_fkey', 'property_media', type_='foreignkey')
    op.create_foreign_key(None, 'property_media', 'properties', ['property_id'], ['id'], source_schema='public', referent_schema='public')
    op.add_column('reviews', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.alter_column('reviews', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('reviews_user_id_fkey', 'reviews', type_='foreignkey')
    op.drop_constraint('reviews_property_id_fkey', 'reviews', type_='foreignkey')
    op.drop_constraint('reviews_booking_id_fkey', 'reviews', type_='foreignkey')
    op.create_foreign_key(None, 'reviews', 'users', ['user_id'], ['telegram_id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'reviews', 'properties', ['property_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'reviews', 'bookings', ['booking_id'], ['id'], source_schema='public', referent_schema='public')
    op.add_column('unavailable_dates', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.drop_constraint('unavailable_dates_property_id_fkey', 'unavailable_dates', type_='foreignkey')
    op.create_foreign_key(None, 'unavailable_dates', 'properties', ['property_id'], ['id'], source_schema='public', referent_schema='public')
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('users', 'updated_at')
    op.drop_constraint(None, 'unavailable_dates', schema='public', type_='foreignkey')
    op.create_foreign_key('unavailable_dates_property_id_fkey', 'unavailable_dates', 'properties', ['property_id'], ['id'])
    op.drop_column('unavailable_dates', 'created_at')
    op.drop_constraint(None, 'reviews', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'reviews', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'reviews', schema='public', type_='foreignkey')
    op.create_foreign_key('reviews_booking_id_fkey', 'reviews', 'bookings', ['booking_id'], ['id'])
    op.create_foreign_key('reviews_property_id_fkey', 'reviews', 'properties', ['property_id'], ['id'])
    op.create_foreign_key('reviews_user_id_fkey', 'reviews', 'users', ['user_id'], ['telegram_id'])
    op.alter_column('reviews', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('reviews', 'updated_at')
    op.drop_constraint(None, 'property_media', schema='public', type_='foreignkey')
    op.create_foreign_key('property_media_property_id_fkey', 'property_media', 'properties', ['property_id'], ['id'])
    op.drop_column('property_media', 'created_at')
    op.drop_constraint(None, 'properties', schema='public', type_='foreignkey')
    op.create_foreign_key('properties_owner_id_fkey', 'properties', 'users', ['owner_id'], ['telegram_id'])
    op.drop_index(op.f('ix_public_properties_price_per_night'), table_name='properties', schema='public')
    op.drop_index(op.f('ix_public_properties_district'), table_name='properties', schema='public')
    op.alter_column('properties', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('properties', 'updated_at')
    op.drop_constraint(None, 'price_rules', schema='public', type_='foreignkey')
    op.create_foreign_key('price_rules_property_id_fkey', 'price_rules', 'properties', ['property_id'], ['id'])
    op.drop_column('price_rules', 'created_at')
    op.drop_constraint(None, 'bookings', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'bookings', schema='public', type_='foreignkey')
    op.create_foreign_key('bookings_property_id_fkey', 'bookings', 'properties', ['property_id'], ['id'])
    op.create_foreign_key('bookings_user_id_fkey', 'bookings', 'users', ['user_id'], ['telegram_id'])
    op.alter_column('bookings', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('bookings', 'updated_at')
    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.VARCHAR(length=191), autoincrement=False, nullable=False),
    sa.Column('next_run_time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('job_state', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='apscheduler_jobs_pkey')
    )
    op.create_index('ix_apscheduler_jobs_next_run_time', 'apscheduler_jobs', ['next_run_time'], unique=False)
    # ### end Alembic commands ###
